feat: use docker compose instead of docker-compose
whatwedo/dde pull request #42
Opened 2023-03-01 09:27 UTC by Ruesa18

fixes: #17

2023-03-01 09:29 UTC, Ruesa18 commented
I will use this in the next few weeks as a test if it works ok :)

2023-03-02 09:28 UTC, renestalder commented
Works flawlessly btw.

When I was setting up Fedora Silverblue on a machine and dde, I wondered, if `docker-compose` is still valid in a certain scenario. There are still two ways of installing composer: Either as a docker plugin (`docker-compose-plugin`), which maches the command `docker compose` are as a separate package (`docker-compose`), where the command stays as `docker-compose`. Therefore, the question for me is, if the whole dde setup should be smart enought to check which of both commands are available? Or can we be sure that `docker-compose` is going away?

2023-03-02 10:20 UTC, Ruesa18 commented
Yeah, I can approve @renestalder's message. For me it has worked flawlessly as well since I changed it.
True, maybe a check would be a good idea. @rugbymauri do you think we could check that on installation and then preset the config? I think it would benefit us if the user could still switch it later or do you see that different? :thinking:

2023-03-14 10:36 UTC, renestalder commented
So, here is the stretch idea, as from my testing of other (dde unrelated) docker compose setups in podman-remote/podman-compose/docker-compose environments:

- Allow to set the binary command manually in an `.env` or similar (in case you have multiple environments installed and need to control it explicitly).
- If not set, check which command exists from the most obvious one to the less obvious one, e.g.  
  `type "docker-compose" > /dev/null`
- Save the command to a variable and run any compose command with this variable.

Just some brainstorming.

e.g. in Make (in case docker is run as make commands. That's what I use in my own projects):

```
COMPOSE_CMD = docker compose

ifeq (,$(type docker-compose &> /dev/null))
	COMPOSE_CMD = docker-compose
endif

setup:
	$(COMPOSE_CMD) run --rm <service> bash -c "<command>"
```

In Bash:

```
if type "docker-compose" > /dev/null; then
  # set variable. Then use variable
fi
```

2023-03-20 08:06 UTC, Ruesa18 commented
@renestalder interesting idea :thinking: 
This could be really helpful for some special projects where you - for some reason - depend on a specific container engine.
Shall we make a separate issue for this and discuss it further over there?

2023-03-20 08:42 UTC, renestalder commented
> @renestalder interesting idea thinking This could be really helpful for some special projects where you - for some reason - depend on a specific container engine. Shall we make a separate issue for this and discuss it further over there?

Sure that. Let's put that in a separate proposal.

2024-02-29 14:22 UTC, s4mpl3d requested changes
@Ruesa18 can you please rebase the pr?

2024-02-29 14:22 UTC, s4mpl3d commented on README.md
>  * [Docker 17.09.0+](https://docs.docker.com/)
@Ruesa18 this version does not work with `docker compose`

2024-02-29 14:30 UTC, s4mpl3d commented
Correction: resolved with #54

2024-02-29 14:30 UTC, closed without merging