feat: Introduction of `DDE_DATA_HOME` and Path Adjustments
whatwedo/dde pull request #65
Opened 2024-01-26 21:04 UTC by sbaerlocher

### Added
- **New Script `createDataHome.sh`**:
  - Introduced a new `_createDataHome` function for creating the `DDE_DATA_HOME` directory and migrating data from `DATA_DIR`.
  - Setup of configuration files in the `DDE_DATA_HOME`.

- **Transition from `DATA_DIR` to `DDE_DATA_HOME` in `checkUpdate.sh`**:
  - Adjusted the script to use `DDE_DATA_HOME` directory instead of `DATA_DIR` for update checks.
  - No functional changes to script behavior.

### Modified
- **Updates in `destroy.sh` and `up.sh`**:
  - Changed from `CERT_DIR` to `DDE_CERT_PATH` for handling SSL certificates.
  - Adjusted path variables without changing the functionality.

- **Environment Variable Updates in `system` Directory (`install.sh`, `env.sh`, `up.sh`)**:
  - Included `DDE_DATA_HOME` and `DDE_CERT_PATH` environment variables, marking `DATA_DIR` and `CERT_DIR` as deprecated.
  - Integrated `_createDataHome` into both `install.sh` and `update.sh`.

### Removed
- **Empty File `data/.gitkeep`**:
  - Deleted the empty placeholder file, as it's no longer needed.

### Refactored
- **`dde.sh` and `docker-compose.yml` Adjustments**:
  - Implemented new environment variables `DDE_DATA_HOME` and `DDE_CERT_PATH`.
  - Updated volume paths in `docker-compose.yml` to align with new directory structures.

2024-03-05 09:23 UTC, robinlehrmann commented
Hello @sbaerlocher I think you need to check the nuke command in this [file](https://github.com/whatwedo/dde/blob/master/commands/system/nuke.sh#L13) as well. :)

2025-09-09 17:12 UTC, s4mpl3d requested changes

2025-09-09 17:12 UTC, s4mpl3d commented on commands/system/env.sh
> +    _logYellow "DATA_DIR (Deprecated, use DDE_DATA_HOME) = ${DATA_DIR}"
@sbaerlocher since its not a user-setting, we can fully remove data_dir from the code and just copy the ./data directory as boilerplate to the new path. This would also allow us to ship some default configuration

2025-09-09 17:12 UTC, s4mpl3d commented on commands/_internals/createDataHome.sh
> +    local nginxConfFile="$DDE_DATA_HOME/data/reverseproxy/etc/nginx/conf.d/dde.conf"
This is not needed, if we treat the data directory in this repo as "defaults"

2026-04-19 19:33 UTC, xarem commented
closed due to v2 refactoring

2026-04-19 19:33 UTC, closed without merging